[package]
name = "figura"
version = "3.2.0"
edition = "2024"
authors = ["Saverio Scagnoli <svscagn@gmail.com>"]
description = "A flexible string template formatting crate"
documentation = "https://docs.rs/figura"
repository = "https://github.com/saverioscagnoli/figura"
homepage = "https://github.com/saverioscagnoli/figura"
license = "MIT"
readme = "README.md"
keywords = ["string", "format", "template"]

exclude = [
    ".gitignore",
    "docs",
    "benchmarks",
    "examples",
    "tests",
    "CHANGELOG.md",
]

[lib]
doctest = false

[dependencies]
foldhash = { version = "0.2.0", optional = true }
zmij = { version = "1.0.23", optional = true }

[features]
default = []
foldhash = ["dep:foldhash"]
zmij = ["dep:zmij"]

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "template_bench"
path = "benchmarks/template_bench.rs"
harness = false
